[package]
name = "init-stage-1"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.10.0", features = ["std"] }
libc = "0.2.177"

[profile.release]
lto = true
codegen-units = 1
strip = true
